# Generated by Django 6.0.2 on 2026-03-23 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_add_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='changed_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 23, 18, 57, 24, 223815, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
