# Generated by Django 6.0.2 on 2026-03-26 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_orderstatushistory_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
