# Generated by Django 6.0.2 on 2026-03-29 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_alter_orderstatushistory_changed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPropertyTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('is_main', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_titles', to='shopping.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product_properties/')),
                ('name', models.CharField(max_length=255)),
                ('change_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('sku', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='shopping.productpropertytitle')),
            ],
        ),
    ]
