# Generated by Django 6.0.2 on 2026-03-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_productpropertytitle_productproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sku',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
