# Generated by Django 6.0.1 on 2026-03-30 07:45

import django.db.models.deletion
from django.db import migrations, models


def seed_product_skus_and_cart(apps, schema_editor):
    Product = apps.get_model('shopping', 'Product')
    ProductSKU = apps.get_model('shopping', 'ProductSKU')
    SKUProductProperty = apps.get_model('shopping', 'SKUProductProperty')
    ProductPropertyTitle = apps.get_model('shopping', 'ProductPropertyTitle')
    ProductProperty = apps.get_model('shopping', 'ProductProperty')
    CartItem = apps.get_model('shopping', 'CartItem')

    for product in Product.objects.all():
        ProductSKU.objects.get_or_create(
            product=product,
            sku=f'{product.product_id}-DEFAULT',
            defaults={'in_stock': True},
        )

    for product in Product.objects.all():
        titles = list(ProductPropertyTitle.objects.filter(product=product).order_by('pk'))
        with_opts = [t for t in titles if ProductProperty.objects.filter(title=t).exists()]
        if len(with_opts) != 1:
            continue
        g = with_opts[0]
        for prop in ProductProperty.objects.filter(title=g):
            code = f'{product.product_id}-P{prop.pk}'
            sku, _ = ProductSKU.objects.get_or_create(
                product=product,
                sku=code,
                defaults={'in_stock': True},
            )
            SKUProductProperty.objects.get_or_create(sku=sku, product_property=prop)

    def find_sku(product_id, prop_ids):
        if not prop_ids:
            for sku in ProductSKU.objects.filter(product_id=product_id):
                if not SKUProductProperty.objects.filter(sku=sku).exists():
                    return sku
            return None
        want = set(int(x) for x in prop_ids)
        for sku in ProductSKU.objects.filter(product_id=product_id):
            linked = set(
                SKUProductProperty.objects.filter(sku=sku).values_list('product_property_id', flat=True)
            )
            if linked == want:
                return sku
        return None

    for ci in CartItem.objects.all():
        ids = list(ci.selected_property_ids or [])
        sku = find_sku(ci.product_id, ids)
        if sku:
            ci.product_sku_id = sku.pk
            ci.save(update_fields=['product_sku_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_cartitem_property_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='configuration_label',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='shopping.product')),
            ],
            options={
                'verbose_name': 'Product SKU',
                'verbose_name_plural': 'Product SKUs',
                'ordering': ['sku'],
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='shopping.productsku'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shopping.productsku'),
        ),
        migrations.CreateModel(
            name='SKUProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.productproperty')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_links', to='shopping.productsku')),
            ],
            options={
                'unique_together': {('sku', 'product_property')},
            },
        ),
        migrations.RunPython(seed_product_skus_and_cart, migrations.RunPython.noop),
    ]
